baseURL: https://www.gailoskitchen.com/
disablePathToLower: true
languageCode: en-us
title: Gailo's Punjabi Kitchen
theme: gochowdown
googleAnalytics: UA-150936119-1
defaultcontentlanguage: en
paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: Gurmail Sohi
  description: Vegetarian Samosa Catering
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent: 
  hidecredits: false
  hidecopyright: false
  showNavTitle: false            # Boolean: show site title in nav bar
  custom_css: 
    - style.css
menu:
  main:
    - name: Call 604-767-8116 to place an order! $1.50 / samosa - $125 for 100. Minimum 50 samosas.
      weight: 1
      url: /
taxonomies:
  category: category
  cusine: cuisine
  tag: tags